# CONFIGURATION GÉNÉRALE
general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

# ARRIÈRE-PLAN
background {
    monitor =
    path = ~/Pictures/hk_2.png   # Chemin vers ton image
    blur_passes = 1 # 0 pour désactiver le flou
}

# CHAMP DE SAISIE DU MOT DE PASSE
input-field {
    monitor =
    size = 500, 50

    outline_thickness = 3

    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true

	fail_color = rgba(200, 50, 50, 0)
	fail_transition = 0
	fail_text = No password?
	check_color = rgba(0, 0, 0, 0)

    outer_color = rgba(255, 150, 150, 0)
    inner_color = rgba(200, 200, 200, 0)
    font_color = rgb(200, 200, 200)
    fade_on_empty = true

    placeholder_text = <i></i>
    hide_input = false

    position = 0, -70
    halign = center
    valign = center
}

# HORLOGE (LABEL)
label {
    monitor =
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 150
    font_family = Monospace
    position = 0, 80
    halign = center
    valign = center
}
