# CONFIGURATION GÉNÉRALE
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

# ARRIÈRE-PLAN
background {
    monitor =
    path = ~/.config/hypr/wallpaper/bg.png
    blur_passes = 1
}

# CHAMP DE SAISIE DU MOT DE PASSE
input-field {
    monitor =
    size = 500, 50
    outline_thickness = 2
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true

    fail_color = rgba(200, 50, 50, 1.0)
    fail_transition = 1
    fail_text = Nop...
    check_color = rgba(0, 0, 0, 0)

    outer_color = rgba(255, 255, 255, 1.0)
    inner_color = rgba(200, 200, 200, 0.2)
    font_color = rgb(200, 200, 200)
    fade_on_empty = true

    placeholder_text = Fou moi la paix 
    hide_input = false

    position = 0, -70
    halign = center
    valign = center
}

# HORLOGE (LABEL)
label {
    monitor =
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 150
    font_family = Monospace
    position = 0, 80
    halign = center
    valign = center
}
